#:schema node_modules/wrangler/config-schema.json
name = "meu-app-svelte"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "remocoespcce"
database_name = "remocoespcce"
database_id = "007bd971-6629-47f9-a635-a54cd978c6c1"